apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yryc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0070-tenant/tkrw-pr712-0075-0070-app/devfile-sample-yryc@sha256:bf14a75cb62ef3418a7d4e7277da8d28903ea74b944433f25d0d860a76a556a1
        name: my-nodejs
        resources: {}
status: {}
